---
variables:
  TF_MIN_VERSION: "0.14"
  AZURERM_PROVIDER_MIN_VERSION: "2.31"

include:
  - template: 'Workflows/Branch-Pipelines.gitlab-ci.yml'
  - project: 'claranet/projects/cloud/azure/terraform/ci'
    ref: examples_allow_failure
    file: '/pipeline.yml'
...
