---
variables:
  TF_MIN_VERSION: "1.0"
  TF_MAX_VERSION: "1.2"
  AZURERM_PROVIDER_MIN_VERSION: "3.0"

include:
  - template: 'Workflows/Branch-Pipelines.gitlab-ci.yml'
  - project: 'claranet/projects/cloud/azure/terraform/ci'
    ref: lint_with_maxtfversion 
    file: '/pipeline.yml'
...
